### ISSUE TITLE
Not working in specific detection website

### ISSUE THREAD

**Issue by sino1641** [daijro/always-on-focus#3]
Hi Daijro,
Thanks for your script but it is not working in 
https://www.daftlogic.com/sandbox-detect-when-page-is-not-visible-using-javascript.htm
I am not pro in JS; it doesn't work when I tried to add all event listeners in your function Kill Event Listeners
Plz take a look at your convenience, thx!

**Comment by 0xJsoul** [comment]
that's weird, because version 1.1 works (https://pastebin.com/raw/S01HMWTF)
maybe the updates broke something?

**Comment by sino1641** [comment]
Thanks! V1.1 works on that website.
Should I close it or wait for your better update?

**Comment by 0xJsoul** [comment]
wait for @daijro to update/fix it

**Comment by daijro** [comment]
Should be fixed in 1.5.
