### ISSUE TITLE
Weird hovering issue

### ISSUE THREAD

**Issue by sn-o-w** [daijro/always-on-focus#4]
Hi there.

Something weird happens while using this user script, and I don't know how to describe properly this issue.

Therefore, please have a look at this: https://youtu.be/tbuvhuOdUCs

I also noticed something extremely similar on the Twitch website: random elements are still hovered on despite the mouse being no longer on those elements. 🤔

**Comment by sn-o-w** [comment]
Reverting the last commit seems to fix the issue, tho. 🤔

**Comment by daijro** [comment]
Fixed in v1.5.1
